# docker-compose.yml
version: "3.9"

services:
  gateway-api:
    build:
      context: .
    environment:
      - chef_url=http://chef-service:50001
      - recipe_url=http://recipe-service:50002
      - review_url=http://review-service:50003

    ports:
      - "8080:8080"
